name: Broadcastery
description: A straight-forward, slimmed down broadcast plugin.
main: com.demigodsrpg.broadcastery.Broadcastery
version: ${project.version}
authors: [_Alex, HmmmQuestionMark]
commands:
    broadcastery:
        usage: /broadcastery [option] [args]
        aliases: [bc]
        permission: broadcastery.admin